#!/usr/bin/env bash
#We create a while loop in which it says to create a loop, print "Best School" and when it equals the value 9 or line 9 print "Hi" below
i=1
while [ $i -le 10 ]
do
  echo "Best School"
  if [ $i == 9 ]
    then
	echo "Hi"
  fi
  (( i++ ))
done
