#!/usr/bin/env bash
# Using the Elif of if we say to put more than one condition
i=1
while [ $i -le 10 ]
do
	echo "Best school"
	if [ $i == 4 ]
	then
		echo "bad luck"
	elif [ $i == 8 ]
	then
		echo "good luck"
	fi
	(( i++ ))
done
