#!/usr/bin/env bash
# We use the Case to say what to write after each specified number
i=1
e=20
while [ $i -le $e ]
do
	echo "$i"
	case $i in
		4) echo "bad luck from China"
			;;
		9) echo "bad luck from Japan "
			;;
		17) echo "bad luck from Italy"
			;;	

	esac
	i=$((i+1))
done
